{% set name = "laserbeamsize" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/laserbeamsize-{{ version }}.tar.gz
  sha256: bf95f8577a255078bea4bc24437a01c7dd702e3febc8259699db7db3d15ed10b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy
    - pytest

test:
  imports:
    - laserbeamsize
  requires:
    - pytest
    - pip
    - python {{ python_min }}
  source_files:
    - tests/test_no_noise.py
  commands:
    - pip check
    - pytest tests/test_no_noise.py

about:
  home: https://github.com/scottprahl/laserbeamsize
  summary: |
    Estimation of beam sizes using the ISO 11146 method and estimates of M² values.

  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://laserbeamsize.readthedocs.io/
  dev_url: https://github.com/scottprahl/laserbeamsize

extra:
  recipe-maintainers:
    - scottprahl
