{% set name = "laserbeamsize" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/laserbeamsize-{{ version }}.tar.gz
  sha256: 9cee76787d1e22b8052d93dd72abc0e522c728ea4eb30e94c7094c446f44d9f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - laserbeamsize
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/scottprahl/laserbeamsize
  summary: |
    Estimation of beam sizes using the ISO 11146 method and estimates of M² values.

  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://laserbeamsize.readthedocs.io/
  dev_url: https://github.com/scottprahl/laserbeamsize

extra:
  recipe-maintainers:
    - scottprahl
