{% set name = "laserbeamsize" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/laserbeamsize-{{ version }}.tar.gz
  sha256: 71a01d08255b7f893b83dabe5dbddde425f0ca5738d5f8109375e79b4a6ff1a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - pillow
    - python >=3.6
    - scipy
    - pytest
    - requests
    - imageio

test:
  imports:
    - laserbeamsize
  requires:
    - pytest
    - pip
  source_files:
    - tests/test_no_noise.py
  commands:
    - pip check
    - pytest tests/test_no_noise.py

about:
  home: https://github.com/scottprahl/laserbeamsize
  summary: |
    Estimation of beam sizes using the ISO 11146 method and estimates of M² values.

  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://laserbeamsize.readthedocs.io/
  dev_url: https://github.com/scottprahl/laserbeamsize

extra:
  recipe-maintainers:
    - scottprahl
